# Generated by Django 4.2.3 on 2023-07-24 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='two_wheeler',
            old_name='userR',
            new_name='userR1',
        ),
    ]
