# Generated by Django 4.2.3 on 2023-07-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_userr_two_wheeler_userr1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_wheeler',
            name='userR1',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
