# Generated by Django 4.2.3 on 2023-07-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_two_wheeler_userr1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='two_wheeler',
            name='Agencyno',
        ),
        migrations.AddField(
            model_name='two_wheeler',
            name='Agencyname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
