# Generated by Django 4.2.3 on 2023-07-25 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_two_wheeler_agencyno_two_wheeler_agencyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='two_wheeler',
            name='userR1',
        ),
    ]
