# Generated by Django 4.1.7 on 2023-08-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_four_wheeler_list_of_vehicles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='two_wheeler',
            name='Vehicleno',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
