# Generated by Django 4.2.3 on 2023-08-02 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_two_wheeler_vehicleno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='two_wheeler',
            new_name='veh_details',
        ),
        migrations.DeleteModel(
            name='four_wheeler',
        ),
        migrations.DeleteModel(
            name='heavy_wheeler',
        ),
    ]
