# Generated by Django 4.2.3 on 2023-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_two_wheeler_veh_details_delete_four_wheeler_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veh_details',
            name='approve',
            field=models.CharField(default='no', max_length=30, null=True),
        ),
    ]
